apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envPromotion
spec:
  generators:
    - git:
        repoURL: https://github.com/dburton18/gitops-cert-level-2-examples.git
        revision: HEAD
        directories:
          - path: environment-promotion/env 
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/dburton18/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
